name: mindmerge
description: A new Flutter project.

version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  socket_io_client: ^1.0.2
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: BalooBhai
      fonts:
        - asset: assets/fonts/BalooBhai-Regular.ttf
    - family: FuzzyBubbles
      fonts:
        - asset: assets/fonts/FuzzyBubbles-Regular.ttf
        - asset: assets/fonts/FuzzyBubbles-Bold.ttf
          weight: 300
